server:
  port: 22333

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shop?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 123456
  thymeleaf:
    cache: false
    mode: HTML5

